spring.application.name=customer-service
spring.datasource.url=jdbc:postgresql://localhost:5432/minibank_customer
spring.datasource.username=minibank_customer_user
spring.datasource.password=Tamil@ibs2001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
